#
## This package is mirrored to an internal NPM registry
#

image: node:18-alpine

stages:
    - release

workflow:
    rules:
        - if: '$CI_COMMIT_TAG =~ /^v\d+.\d+.\d+/'
        - if: '$CI_MANUAL_TRIGGER'

release:
    stage: release
    script:
        - npm ci
        - npm run build
        - npm publish
