#
## This package is mirrored to an internal NPM registry
#

image: node:18-alpine

stages:
    - release

release-latest:
    stage: release
    rules:
        - if: '$CI_COMMIT_TAG =~ /^v\d+.\d+.\d+-beta\.\d+/'
          when: never
        - if: '$CI_COMMIT_TAG =~ /^v\d+.\d+.\d+/'
        - if: '$CI_MANUAL_TRIGGER'
    script:
        - npm ci
        - npm run build
        - npm publish

release-beta:
    stage: release
    rules:
        - if: '$CI_COMMIT_TAG =~ /^v\d+.\d+.\d+-beta\.\d+/'
        - if: '$CI_MANUAL_TRIGGER'
    script:
        - npm ci
        - npm run build
        - npm publish --tag beta
